In [1]:
import pandas as pd
from sqlalchemy import create_engine

pd.set_option('display.max_rows',30)
pd.set_option('display.max_columns',None)

In [2]:
#esta es la ip para conectar a la bbdd y hay que darle paso en OVHcloud
!curl ipecho.net/plain #34.125.139.147

34.139.187.100

In [3]:
# Configuración de la conexión a PostgreSQL
usuario = "admin"
contrasena = "Admin123"
servidor = "lm1875501-001.eu.clouddb.ovh.net"
puerto = "35256"
base_datos = "my_wyscout"
# Crea la cadena de conexión
conexion_str = f'postgresql+psycopg2://{usuario}:{contrasena}@{servidor}:{puerto}/{base_datos}'

In [7]:
# Cargar los datos de la tabla jugadores que queremos analizar
query = "SELECT * \
         FROM jugadores \
         WHERE \"Competición\" = '2RFEF' AND \
               \"Posición Principal\" = 'Central' AND \
               \"Minutos jugados\" <= 300 AND \
               (\"Altura\" BETWEEN 180 AND 185 OR \"Altura\" = 0) AND \
               \"Edad\" BETWEEN 24 AND 27  \
        ;"
df = pd.read_sql(query, conexion_str)
df.drop(columns='Equipo', inplace=True)
df.rename(columns={'Equipo durante el período seleccionado': 'Equipo'}, inplace=True)

In [5]:
df.head(2)

,Jugador,Equipo,Posición específica,Edad,Valor de mercado (Transfermarkt),Vencimiento contrato,Partidos jugados,Minutos jugados,Goles,xG,Asistencias,xA,Duelos/90,Duelos ganados %,País de nacimiento,Pasaporte,Pie,Altura,Peso,En prestamo,Acciones defensivas realizadas/90,Duelos defensivos/90,Duelos defensivos ganados %,Duelos aéreos en los 90,Duelos aéreos ganados %,Entradas/90,Posesión conquistada después de una entrada,Tiros interceptados/90,Interceptaciones/90,Posesión conquistada después de una interceptación,Faltas/90,Tarjetas amarillas,Tarjetas amarillas/90,Tarjetas rojas,Tarjetas rojas/90,Acciones de ataque exitosas/90,Goles/90,Goles (excepto los penaltis),"Goles, excepto los penaltis/90",xG/90,Goles de cabeza,Goles de cabeza/90,Remates,Remates/90,Tiros a la portería %,Goles hechos %,Asistencias/90,Centros/90,Precisión centros %,Centros desde la banda izquierda/90,Precisión centros desde la banda izquierda %,Centros desde la banda derecha/90,Precisión centros desde la banda derecha %,Centros al área pequeña/90,Regates/90,Regates realizados %,Duelos atacantes/90,Duelos atacantes ganados %,Toques en el área de penalti/90,Carreras en progresión/90,Aceleraciones/90,Pases recibidos /90,Pases largos recibidos/90,Faltas recibidas/90,Pases/90,Precisión pases %,Pases hacia adelante/90,Precisión pases hacia adelante %,Pases hacia atrás/90,Precision pases hacia atrás %,Pases laterales/90,Precisión pases laterales %,Pases cortos / medios /90,Precisión pases cortos / medios %,Pases largos/90,Precisión pases largos %,"Longitud media pases, m","Longitud media pases largos, m",xA/90,Asistencias/90.1,Second assists/90,Third assists/90,Desmarques/90,Precisión desmarques %,Jugadas claves/90,Pases en el último tercio/90,Precisión pases en el último tercio %,Pases al área de penalti/90,Pases hacía el área pequeña %,Pases en profundidad/90,Precisión pases en profundidad %,Ataque en profundidad/90,Centros desde el último tercio/90,Pases progresivos/90,Precisión pases progresivos %,Goles recibidos,Goles recibidos/90,Remates en contra,Remates en contra/90,Porterías imbatidas en los 90,Paradas %,xG en contra,xG en contra/90,Goles evitados,Goles evitados/90,Pases hacía atrás recibidos del arquero/90,Salidas/90,Duelos aéreos en los 90.1,Tiros libres/90,Tiros libres directos/90,Tiros libres directos %,Córneres/90,Penaltis a favor,Penaltis realizados %,Total Distance per 90,Running Distance per 90 (15-20 km/h),HSR Distance per 90 (20-25 km/h),Sprinting Distance per 90 (+25 km/h),HI Distance per 90 (+20 km/h),Meter/Min,Max Speed (km/h),Count Medium Acceleration per 90 (1.5 m/s² to 3 m/s²),Count High Acceleration per 90 (+3 m/s²),Count Medium Deceleration per 90 (-1.5 m/s² to -3 m/s²),Count High Deceleration per 90 (-3 m/s²),Count HSR per 90 (20-25 km/h),Count Sprint per 90 (+25 km/h),Count HI per 90 (+20 km/h),Competición,Temporada,Pais_Comp,Flag,Posición Principal,Fecha_Actualizacion
0,Pelayo Suárez,Pontevedra,RCB,26,200000,None,2,171,0,0.0,0,0.0,17.89,44.12,Spain,Spain,derecho,183,84,no,8.95,7.37,71.43,5.26,30.0,0.53,0.94,0.53,3.16,5.63,1.05,2,1.05,0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.11,25.0,0.53,1.05,0.0,29.47,0.00,0.00,44.74,90.59,17.89,79.41,3.16,83.33,18.95,100.00,35.79,94.12,8.95,76.47,27.11,39.56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.95,82.35,0.53,0.0,1.05,0.0,0.53,0.0,12.63,91.67,0,None,0,None,0,0.0,0.0,0.0,None,None,2.11,None,None,0.0,0.0,0.0,0.0,0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2RFEF,2024-2025,ESP,https://images.fotmob.com/image_resources/logo...,Central,2024-12-05 21:36:01.158249
1,Isma Aizpiri,UD Sanse,RCB,26,150000,2025-06-30,6,297,0,0.0,0,0.0,10.00,66.67,Spain,Spain,derecho,182,72,no,5.45,3.64,50.00,2.42,87.5,0.30,0.45,0.30,3.33,4.93,0.91,1,0.30,0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.42,62.5,0.00,0.30,0.0,33.03,0.61,1.21,44.24,90.41,19.70,83.08,5.45,100.00,16.36,98.15,41.21,94.85,3.03,30.00,19.62,25.59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.85,56.25,0.00,0.0,0.00,0.0,0.00,0.0,3.94,61.54,0,None,0,None,0,0.0,0.0,0.0,None,None,2.73,None,None,0.0,0.0,0.0,0.0,0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2RFEF,2024-2025,ESP,https://images.fotmob.com/image_resources/logo...,Central,2024-12-05 21:36:01.158249

In [ ]:
# Aplicar las reglas y calcular la puntuación
#df_datos =  df[(df['Competición']  == "2RFEF" )]
#df_datos.head()

In [9]:
# Aplicar las reglas y calcular la puntuación
#CENTRAL
df['Puntuacion'] = (
                    (df['Tiros interceptados/90'] > 1.0) * 1.7 +
                    (df['Interceptaciones/90'] > 4.5) * 1.4 +
                    (df['Posesión conquistada después de una interceptación'] > 8.5) * 1.3 +
                    (df['Acciones defensivas realizadas/90'] > 8.5) * 1.2 +
                    (df['Duelos aéreos/90'] > 4.5) * 1.1 +
                    (df['Duelos aéreos ganados %'] > 60) * 1.1
                    )

# Ordenar jugadores por puntuación
df = df.sort_values(by='Puntuacion', ascending=False)

df = df.drop_duplicates()

# Mostrar los 10 jugadores con mayor puntuación
df[['Jugador', 'Equipo', 'Minutos jugados', 'Edad', 'Altura', 'Puntuacion']]

# Guardar el resultado en una tabla nueva en la base de datos (opcional)
#df.to_sql('jugadores_priorizados', conexion_str, if_exists='replace', index=False)

          Jugador          Equipo  Minutos jugados  Edad  Altura  Puntuacion
5   Carlos Llamas    Unión Adarve              262    25     185         4.8
4          Morago          Subiza              192    27       0         4.3
0   Pelayo Suárez      Pontevedra              171    26     183         2.3
2  Jorge Cortázar  Peña Deportiva               81    26       0         2.3
1    Isma Aizpiri        UD Sanse              297    26     182         1.1
3     M. Voltarel        Anguiano               10    27       0         0.0